"""add savings goals table

Revision ID: a7d41da94333
Revises: 8bd36d94b772
Create Date: 2026-09-17 20:41:37.901283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d41da94333'
down_revision: Union[str, Sequence[str], None] = '8bd36d94b772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_goals', sa.Column('goal_name', sa.String(length=150), nullable=False))
    op.add_column('savings_goals', sa.Column('saved_amount', sa.Float(), nullable=False))
    op.add_column('savings_goals', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('check_savings_current_non_negative'), 'savings_goals', type_='check')
    op.create_check_constraint('check_savings_saved_non_negative', 'savings_goals', 'saved_amount >= 0')
    op.drop_column('savings_goals', 'status')
    op.drop_column('savings_goals', 'current_amount')
    op.drop_column('savings_goals', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_goals', sa.Column('name', sa.VARCHAR(length=150), nullable=False))
    op.add_column('savings_goals', sa.Column('current_amount', sa.FLOAT(), nullable=False))
    op.add_column('savings_goals', sa.Column('status', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint('check_savings_saved_non_negative', 'savings_goals', type_='check')
    op.create_check_constraint(op.f('check_savings_current_non_negative'), 'savings_goals', 'current_amount >= 0')
    op.drop_column('savings_goals', 'description')
    op.drop_column('savings_goals', 'saved_amount')
    op.drop_column('savings_goals', 'goal_name')
    # ### end Alembic commands ###
